#!/bin/bash
set -e;


if [ -n "${POSTGRES_N8N_USER:-}" ] && [ -n "${POSTGRES_N8N_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_N8N_DB" <<-EOSQL
		CREATE USER ${POSTGRES_N8N_USER} WITH PASSWORD '${POSTGRES_N8N_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_N8N_DB} TO ${POSTGRES_N8N_USER};
		GRANT CREATE ON SCHEMA public TO ${POSTGRES_N8N_USER};
	EOSQL
else
	echo "SETUP INFO: No N8N Environment variables given!"

if [ -n "${POSTGRES_APOSTIFY_USER:-}" ] && [ -n "${POSTGRES_APOSTIFY_PASSWORD:-}" ]; then
	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_APOSTIFY_DB" <<-EOSQL
		CREATE USER ${POSTGRES_APOSTIFY_USER} WITH PASSWORD '${POSTGRES_APOSTIFY_PASSWORD}';
		GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_APOSTIFY_DB} TO ${POSTGRES_APOSTIFY_USER};
		GRANT CREATE ON SCHEMA public TO ${POSTGRES_APOSTIFY_USER};
	EOSQL
else
	echo "SETUP INFO: No Apostify Environment variables given!"
fi
